# Generated by Django 3.2 on 2021-04-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=80)),
                ('customer_email', models.EmailField(max_length=120)),
                ('customer_mobile', models.IntegerField(max_length=40)),
                ('status', models.CharField(choices=[('C', 'CREATED'), ('P', 'PAYED'), ('R', 'REJECTED')], default='C', max_length=1)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
